function out = MEMdphidbeta_decay_diag_diag_1(in1,in2)
%MEMDPHIDBETA_DECAY_DIAG_DIAG_1
%    out = MEMDPHIDBETA_DECAY_DIAG_DIAG_1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    05-Dec-2016 13:01:39

M_m0= in1(1);
M_delta= in1(2);
b_m0= in2(1);
b_delta= in2(2);
out = zeros(4,1);
out(1) = 1;
out(4) = 1;
out = reshape(out,[2  2]);