function out = MEMddds_tdpdpdp_decay_diag_diag_1(in1)
%MEMDDDS_TDPDPDP_DECAY_DIAG_DIAG_1
%    out = MEMDDDS_TDPDPDP_DECAY_DIAG_DIAG_1(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    05-Dec-2016 13:01:38

p_m0= in1(1);
p_delta= in1(2);
out = zeros(0,1);
out = reshape(out,[0  1  2  2  2]);