function out = MEMphi_decay_diag_diag_1(in1,in2)
%MEMPHI_DECAY_DIAG_DIAG_1
%    out = MEMPHI_DECAY_DIAG_DIAG_1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    05-Dec-2016 13:01:38

M_m0= in1(1);
M_delta= in1(2);
b_m0= in2(1);
b_delta= in2(2);
out = zeros(2,1);
out(1) = M_m0 + b_m0;
out(2) = M_delta + b_delta;
out = reshape(out,[2  1]);