function out = MEMddbetadxidxi_transfection_diag_diag_1(in1)
%MEMDDBETADXIDXI_TRANSFECTION_DIAG_DIAG_1
%    out = MEMDDBETADXIDXI_TRANSFECTION_DIAG_DIAG_1(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    05-Dec-2016 13:02:07

M_t0= in1(1);
M_m0_kTL= in1(2);
M_beta= in1(3);
M_delta= in1(4);
C_t0= in1(5);
C_m0_kTL= in1(6);
C_beta= in1(7);
out = zeros(196,1);
out = reshape(out,[4  7  7]);