function out = MEMds_tdp_transfection_diag_diag_1(in1)
%MEMDS_TDP_TRANSFECTION_DIAG_DIAG_1
%    out = MEMDS_TDP_TRANSFECTION_DIAG_DIAG_1(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    05-Dec-2016 13:02:08

p_t0= in1(1);
p_m0_kTL= in1(2);
p_beta= in1(3);
p_delta= in1(4);
out = zeros(4,1);
out = reshape(out,[1  1  4]);