function out = MEMdds_ndpdp_toy_diag_1(in1)
%MEMDDS_NDPDP_TOY_DIAG_1
%    out = MEMDDS_NDPDP_TOY_DIAG_1(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    05-Dec-2016 13:01:11

p_x0= in1(1);
p_d= in1(2);
out = zeros(4,1);
out = reshape(out,[1  1  2  2]);